### ISSUE TITLE
bug : replace dialog box not disappearing after pressing ok button

### ISSUE THREAD

**Issue by lalthomas** [mjdescy/TodoTxtMac#66] opened 2015-03-19 11:44 UTC
Hi @mjdescy 

I have searched for a project name and the replace text was also a project name (it was like replacing a project with another one),but the replace dialog box was not disappearing after pressing the ok button. I haven't used keyboard shortcuts.

Mac OS Version : 10.10 
Software Version 1.5.0

**Comment by mjdescy** [comment] 2015-03-19 18:19
Hi, @lalthomas. That stumps me. I can't reproduce that bug. I retested replacing project names today, and still can't get the dialog box to stick.

**Comment by lalthomas** [comment] 2015-03-19 18:34
@mjdescy I am sorry, i am also not able to reproduce it. It occured only once. Anyway the scenario was like I did the replacement on items on a filtered page. I tired the same again but it was ok afterwards.

**Comment by mjdescy** [comment] 2015-03-20 20:51
Good to hear. Maybe it was an obscure Cocoa runtime error. I will keep this issue open for a little while in case any other users comment on it. If no one else reports it, I will close it.

**Comment by Brixy** [comment] 2015-04-07 11:25
Hi @mjdescy and @lalthomas.

Maybe this is/was related to [issue 60](https://github.com/mjdescy/TodoTxtMac/issues/60).

My issue disappeared after the update to 1.5.0, but it has reappeared unfortunately.

**Closed** 2016-03-18 23:48 UTC
