### ISSUE TITLE
Weird glitch when editing items on macOS Sierra

### ISSUE THREAD

**Issue by Querschlag** [mjdescy/TodoTxtMac#121] opened 2017-01-20 14:33 UTC
Since I upgraded to Sierra I get a black line when selecting an entry for editing.
I can reveal some of the text when selecting it with the cursor.
Also when I try to type my key presses are interpreted as Shortcuts for actions like "Add new Task" ect. at not as text input.

![screen shot 2017-01-20 at 15 28 05](https://cloud.githubusercontent.com/assets/1651468/22152874/174a3464-df25-11e6-8f7b-4e404744ac6a.png)

**Comment by mjdescy** [comment] 2017-01-20 21:50
This is a duplicate of Issue #118. A fix will be issued shortly.

**Closed by mjdescy** 2017-01-20 21:50 UTC
Labels: duplicate
