### ISSUE TITLE
Due date picker shows 1 day before date entered

### ISSUE THREAD

**Issue by robertvanbregt** [mjdescy/TodoTxtMac#69] opened 2015-05-18 20:21 UTC
If I type 8, it shows 7.
If I use the controls to show 8, it saves 9.

**Comment by mjdescy** [comment] 2015-05-18 20:44
I am not seeing that behavior. What time zone are you in? What dates are you typing in? I have fixed bugs related to Daylight Savings Time and other time zone-related differences.

**Comment by robertvanbregt** [comment] 2015-05-19 04:00
I use Europe/Amsterdam timezone.

This is the sequence of activities:

### Create new task

![todo1](https://cloud.githubusercontent.com/assets/559346/7695161/8f450bb4-fdeb-11e4-8773-99ec4cc2c950.png)

### Add due date through menu

As you can see, the date already shows as **yesterday**

![todo2](https://cloud.githubusercontent.com/assets/559346/7695164/929b1740-fdeb-11e4-9beb-cef31539e6da.png)

### Use up arrow in UI to increase due date with 3 days

It shows 3 days from **yesterday**

![todo3](https://cloud.githubusercontent.com/assets/559346/7695192/f3c9301a-fdeb-11e4-9a41-7d924f4c4155.png)

### The result

3 Days from today, but different than shown in date picker.

![todo4](https://cloud.githubusercontent.com/assets/559346/7695211/236b4c36-fdec-11e4-8f0b-7c06f8364180.png)

**Comment by mjdescy** [comment] 2015-05-19 14:28
@robertvanbregt Thanks for that detailed bug report. I have confirmed that there is a bug and it appears to affect the eastern hemisphere only. Changing my time zone does have an unintended effect on the date displayed by the "set due date" date picker. I will try to track down the problem and solve it for you and your half of the planet. :-)

**Comment by mjdescy** [comment] 2015-05-20 14:36
Closed in Version 1.5.1.

**Closed by mjdescy** 2015-05-20 14:36 UTC
Labels: bug
